wget -I /Users/richardfeder/Documents/ciber/data/catalogs/unWISE/raw_neo8/ https://portal.nersc.gov/project/cosmo/data/unwise/neo8/unwise-catalog/cat/1906p075.1.cat.fits
wget -I /Users/richardfeder/Documents/ciber/data/catalogs/unWISE/raw_neo8/ https://portal.nersc.gov/project/cosmo/data/unwise/neo8/unwise-catalog/cat/1906p075.2.cat.fits
wget -I /Users/richardfeder/Documents/ciber/data/catalogs/unWISE/raw_neo8/ https://portal.nersc.gov/project/cosmo/data/unwise/neo8/unwise-catalog/cat/1922p075.1.cat.fits
wget -I /Users/richardfeder/Documents/ciber/data/catalogs/unWISE/raw_neo8/ https://portal.nersc.gov/project/cosmo/data/unwise/neo8/unwise-catalog/cat/1922p075.2.cat.fits
wget -I /Users/richardfeder/Documents/ciber/data/catalogs/unWISE/raw_neo8/ https://portal.nersc.gov/project/cosmo/data/unwise/neo8/unwise-catalog/cat/1914p090.1.cat.fits
wget -I /Users/richardfeder/Documents/ciber/data/catalogs/unWISE/raw_neo8/ https://portal.nersc.gov/project/cosmo/data/unwise/neo8/unwise-catalog/cat/1914p090.2.cat.fits
wget -I /Users/richardfeder/Documents/ciber/data/catalogs/unWISE/raw_neo8/ https://portal.nersc.gov/project/cosmo/data/unwise/neo8/unwise-catalog/cat/1899p090.1.cat.fits
wget -I /Users/richardfeder/Documents/ciber/data/catalogs/unWISE/raw_neo8/ https://portal.nersc.gov/project/cosmo/data/unwise/neo8/unwise-catalog/cat/1899p090.2.cat.fits
wget -I /Users/richardfeder/Documents/ciber/data/catalogs/unWISE/raw_neo8/ https://portal.nersc.gov/project/cosmo/data/unwise/neo8/unwise-catalog/cat/1891p075.1.cat.fits
wget -I /Users/richardfeder/Documents/ciber/data/catalogs/unWISE/raw_neo8/ https://portal.nersc.gov/project/cosmo/data/unwise/neo8/unwise-catalog/cat/1891p075.2.cat.fits
wget -I /Users/richardfeder/Documents/ciber/data/catalogs/unWISE/raw_neo8/ https://portal.nersc.gov/project/cosmo/data/unwise/neo8/unwise-catalog/cat/1808p060.1.cat.fits
wget -I /Users/richardfeder/Documents/ciber/data/catalogs/unWISE/raw_neo8/ https://portal.nersc.gov/project/cosmo/data/unwise/neo8/unwise-catalog/cat/1808p060.2.cat.fits
wget -I /Users/richardfeder/Documents/ciber/data/catalogs/unWISE/raw_neo8/ https://portal.nersc.gov/project/cosmo/data/unwise/neo8/unwise-catalog/cat/1913p060.1.cat.fits
wget -I /Users/richardfeder/Documents/ciber/data/catalogs/unWISE/raw_neo8/ https://portal.nersc.gov/project/cosmo/data/unwise/neo8/unwise-catalog/cat/1913p060.2.cat.fits
